version: '2'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./data/mongo:/data/db
      - ./data/mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express:0.54
    restart: always
    container_name: mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER_WAIT_MAX_TRIES: 30
    depends_on:
      - "mongo"
    links:
      - "mongo"
  fastapi:
      build:
        context: ./
        dockerfile: backend.dockerfile
      volumes:
        - './backend:/app'
      ports:
        - 8000:8000
      environment:
        MONGODB_HOST: mongo
        MONGODB_PORT: 27017
        MONGODB_USER: admin
        MONGODB_PASSWORD: admin
        PYTHONPATH: /app
  react:
    build:
      context: ./
      dockerfile: frontend.dockerfile
    ports:
      - 3000:3000